par = list()

par[["ACC"]] = "adipose"        
par[["CESC"]] = "reproductive"  
par[["CHOL"]] = "GI tract"      
par[["DLBC"]] = "lymph"         
par[["ESCA"]] = "GI tract" 
par[["KICH"]] = "kidney"        
par[["KIRP"]] = "kidney"        
par[["GBM"]] = "brain"          
par[["LGG"]] = "brain"
par[["LIHC"]] = "liver"
par[["LUSC"]] = "lung"
par[["MESO"]] = "heart"         
par[["OV"]] = "reproductive" 
par[["PAAD"]] = "pancreas" 
par[["PCPG"]] = "pns"       
par[["SKCM"]] = "epidermis"
par[["STAD"]] = "GI tract"      
par[["TGCT"]] = "reproductive"
par[["THCA"]] = "thyroid"
par[["THYM"]] = "thymus"
par[["UCS"]] = "urinary"
par[["UVM"]] = "epidermis"          

par[["NORMAL"]] = "NORMAL"

#inner parts of tree
par[["brain"]] = "neural tube" 
par[["spinal cord"]] = "neural tube" 
par[["pns"]] = "neural crest" 
par[["head mesenchyme"]] = "neural crest" 
par[["epidermis"]] = "surface ectoderm" 
par[["bone"]] = "paraxial mesoderm" 
par[["cartilage"]] = "paraxial mesoderm"
par[["skeletal muscle"]] = "paraxial mesoderm"  
par[["tendon and ligament"]] = "paraxial mesoderm"
par[["dermis"]] = "paraxial mesoderm"
par[["reproductive"]] = "intermediate mesoderm" 
par[["urinary"]] = "intermediate mesoderm" 
par[["kidney"]] = "intermediate mesoderm" 
par[["adipose"]] = "lateral plate mesoderm" 
par[["blood"]] = "lateral plate mesoderm" 
par[["endothelium"]] = "lateral plate mesoderm" 
par[["lymph"]] = "lateral plate mesoderm" 
par[["smooth muscle"]] = "lateral plate mesoderm" 
par[["heart"]] = "lateral plate mesoderm" 
par[["limb"]] = "lateral plate mesoderm" 
par[["thymus"]] = "gut tube" 
par[["lung"]] = "gut tube" 
par[["pancreas"]] = "gut tube" 
par[["prostate"]] = "gut tube" 
par[["GI tract"]] = "gut tube" 
par[["liver"]] = "gut tube" 
par[["thyroid"]] = "gut tube" 

par[["neural tube"]] = "neural ectoderm" 
par[["neural crest"]] = "neural ectoderm" 
par[["surface ectoderm"]] = "surface ectoderm " 

par[["paraxial mesoderm"]] = "paraxial mesoderm " 
par[["intermediate mesoderm"]] = "intermediate mesoderm " 
par[["lateral plate mesoderm"]] = "lateral plate mesoderm " 
par[["gut tube"]] = "gut tube " 

par[["neural ectoderm"]] = "ectoderm" 
par[["surface ectoderm "]] = "ectoderm" 
par[["paraxial mesoderm "]] = "mesoderm"
par[["intermediate mesoderm "]] = "mesoderm"
par[["lateral plate mesoderm "]] = "mesoderm"
par[["gut tube "]] = "endoderm"

par[["ectoderm"]] = "tumor cell"
par[["mesoderm"]] = "tumor cell"
par[["endoderm"]] = "tumor cell"

#####################################################


par[["NORMAL_ACC"]] = "NORMAL_adipose"        #adrenal glands?
par[["NORMAL_CESC"]] = "NORMAL_reproductive"  
par[["NORMAL_CHOL"]] = "NORMAL_GI tract"      #bile ducts?
par[["NORMAL_DLBC"]] = "NORMAL_lymph"       
par[["NORMAL_ESCA"]] = "NORMAL_GI tract" #esophagus?
par[["NORMAL_KICH"]] = "NORMAL_kidney"        
par[["NORMAL_KIRP"]] = "NORMAL_kidney"        
par[["NORMAL_GBM"]] = "NORMAL_brain"          
par[["NORMAL_LGG"]] = "NORMAL_brain"
par[["NORMAL_LIHC"]] = "NORMAL_liver"
par[["NORMAL_LUSC"]] = "NORMAL_lung"
par[["NORMAL_MESO"]] = "NORMAL_heart"         #affects heart, lungs, and chest
par[["NORMAL_OV"]] = "NORMAL_reproductive" 
par[["NORMAL_PAAD"]] = "NORMAL_pancreas" 
par[["NORMAL_PCPG"]] = "NORMAL_pns"       #again, affects adrenal glands
par[["NORMAL_SKCM"]] = "NORMAL_epidermis"
par[["NORMAL_STAD"]] = "NORMAL_GI tract"      #affects stomach
par[["NORMAL_TGCT"]] = "NORMAL_reproductive"
par[["NORMAL_THCA"]] = "NORMAL_thyroid"
par[["NORMAL_THYM"]] = "NORMAL_thymus"
par[["NORMAL_UCS"]] = "NORMAL_urinary"
par[["NORMAL_UVM"]] = "NORMAL_epidermis"          #affects eye??


#inner parts of tree
par[["NORMAL_brain"]] = "NORMAL_neural tube" 
par[["NORMAL_spinal cord"]] = "NORMAL_neural tube" 
par[["NORMAL_pns"]] = "NORMAL_neural crest" 
par[["NORMAL_head mesenchyme"]] = "NORMAL_neural crest" 
par[["NORMAL_epidermis"]] = "NORMAL_surface ectoderm" 
par[["NORMAL_bone"]] = "NORMAL_paraxial mesoderm" 
par[["NORMAL_cartilage"]] = "NORMAL_paraxial mesoderm"
par[["NORMAL_skeletal muscle"]] = "NORMAL_paraxial mesoderm"  
par[["NORMAL_tendon and ligament"]] = "NORMAL_paraxial mesoderm"
par[["NORMAL_dermis"]] = "NORMAL_paraxial mesoderm"
par[["NORMAL_reproductive"]] = "NORMAL_intermediate mesoderm" 
par[["NORMAL_urinary"]] = "NORMAL_intermediate mesoderm" 
par[["NORMAL_kidney"]] = "NORMAL_intermediate mesoderm" 
par[["NORMAL_adipose"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_blood"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_endothelium"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_lymph"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_smooth muscle"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_heart"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_limb"]] = "NORMAL_lateral plate mesoderm" 
par[["NORMAL_thymus"]] = "NORMAL_gut tube" 
par[["NORMAL_lung"]] = "NORMAL_gut tube" 
par[["NORMAL_pancreas"]] = "NORMAL_gut tube" 
par[["NORMAL_prostate"]] = "NORMAL_gut tube" 
par[["NORMAL_GI tract"]] = "NORMAL_gut tube" 
par[["NORMAL_liver"]] = "NORMAL_gut tube" 
par[["NORMAL_thyroid"]] = "NORMAL_gut tube" 

par[["NORMAL_neural tube"]] = "NORMAL_neural ectoderm" 
par[["NORMAL_neural crest"]] = "NORMAL_neural ectoderm" 
par[["NORMAL_surface ectoderm"]] = "NORMAL_surface ectoderm " 

par[["NORMAL_paraxial mesoderm"]] = "NORMAL_paraxial mesoderm " 
par[["NORMAL_intermediate mesoderm"]] = "NORMAL_intermediate mesoderm " 
par[["NORMAL_lateral plate mesoderm"]] = "NORMAL_lateral plate mesoderm " 
par[["NORMAL_gut tube"]] = "NORMAL_gut tube " 

par[["NORMAL_neural ectoderm"]] = "NORMAL_ectoderm" 
par[["NORMAL_surface ectoderm "]] = "NORMAL_ectoderm" 
par[["NORMAL_paraxial mesoderm "]] = "NORMAL_mesoderm"
par[["NORMAL_intermediate mesoderm "]] = "NORMAL_mesoderm"
par[["NORMAL_lateral plate mesoderm "]] = "NORMAL_mesoderm"
par[["NORMAL_gut tube "]] = "NORMAL_endoderm"

par[["NORMAL_ectoderm"]] = "NORMAL_tumor cell"
par[["NORMAL_mesoderm"]] = "NORMAL_tumor cell"
par[["NORMAL_endoderm"]] = "NORMAL_tumor cell"
